### ISSUE TITLE
Kanban Board Group Setup 

### ISSUE THREAD

**Issue by Johnadibe** [Johnadibe/space-travelers-hub#24]
[Link to gitHub project](https://github.com/Johnadibe/space-travelers-hub/projects/1).

- We are two persons in the group:
- John Adibe
- Mark Fenekayas

**Comment by andersonlebon** [comment]
## Hi team @Johnadibe  and @Fene-87 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes ♻️
https://github.com/Johnadibe/space-travelers-hub/issues/19
- [ ] Kindly note that this issue needs to be included in your Kanbanboard as is not assigned to TEAM member #3. kindly add it to your track board and assign it to one of your members

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Johnadibe** [comment]
Yeah, I didn't see it when I deleted for the Dragon Tasks.
Thank you @andersonlebon😊
